DQL_TEMPLATES = {
    "T1190": {"name": "Exploit Public-Facing Application",
        "query": 'source="{log_source}" AND http_status=200 AND uri_path contains "admin" AND response_size>10000'},
    "T1486": {"name": "Data Encrypted for Impact (Ransomware)",
        "query": 'source="{log_source}" AND event_type="file_modify" AND file_extension in (".locked",".encrypted") AND file_count_per_min>50'},
    "T1041": {"name": "Exfiltration Over C2 Channel",
        "query": 'source="{log_source}" AND direction="outbound" AND bytes_out>100000000 AND dest_reputation="unknown"'},
    "T1059": {"name": "Command and Scripting Interpreter",
        "query": 'source="{log_source}" AND process_name in ("cmd.exe","powershell.exe","bash") AND parent_process="webserver"'},
    "T1552": {"name": "Unsecured Credentials",
        "query": 'source="{log_source}" AND file_accessed contains "credentials" AND process_name!="expected_admin_tool"'},
    "T1021": {"name": "Remote Services (Lateral Movement)",
        "query": 'source="{log_source}" AND event_type="logon" AND logon_type="network" AND source_host!=dest_host'},
    "T1555.003": {"name": "Credentials from Web Browsers",
        "query": 'source="{log_source}" AND file_path contains "Login Data" AND process_name!="chrome.exe"'},
    "T1090": {"name": "Proxy",
        "query": 'source="{log_source}" AND dest_port=1080 AND protocol="socks5"'},
    "T1059.001": {"name": "PowerShell",
        "query": 'source="{log_source}" AND process_name="powershell.exe" AND command_line contains "-enc"'},
    "T1003": {"name": "OS Credential Dumping",
        "query": 'source="{log_source}" AND process_name="lsass.exe" AND event_type="access"'},
}
